# Generated by Django 3.1.2 on 2020-10-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=6, unique=True)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('ups', models.IntegerField(blank=True, default=0)),
                ('subreddit', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('num_comments', models.PositiveSmallIntegerField(default=0)),
                ('url', models.URLField(verbose_name='post_url')),
                ('sentiment', models.CharField(max_length=10, null=False))
            ],
            options={
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tokens', models.TextField(null=True)),
                ('stems', models.JSONField(null=True, verbose_name='post stems')),
                ('pos_tags', models.JSONField(null=True, verbose_name='post part of speech tags')),
                ('lemma', models.JSONField(null=True, verbose_name='post lemma')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
