# Generated by Django 3.1.1 on 2020-10-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(max_length=10, null=False)
        )
    ]